### ISSUE TITLE
Check Crew Cost Calculation

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#10]
Crew cost calculation not showing

**Comment by jsomara** [comment]
Crew cost still has Mcr units in it, which is probably why this isn't working!

**Comment by jsomara** [comment]
I removed Mcr from the CSV, but the problem persists. Most likely the error is that these are decimal values, but we parse these as integers

See starshipCtrl lines 41 for what I mean

**Comment by seiyria** [comment]
There's no expression bound here:

```
<span ng-bind="ship.hull.Crew || 0"></span> (cost <span ng-bind=""></span>Cr/m);
```

Could that be why?

**Comment by seiyria** [comment]
#rekt

**Comment by jsomara** [comment]
I believe I fixed this for most of the facilities; some look like they are just parsing incorrectly still. There is now a new block that calculates cost for Space, Crew and Luxury by crew
