### ISSUE TITLE
Facilities aren’t affecting CPU, CU, or cost

### ISSUE THREAD

**Issue by seiyria** [herosheets/woin-starships#20]

**Comment by seiyria** [comment]
This is probably related to:
- bad data
- they don't have a CPU field

**Comment by seiyria** [comment]
If space/crew can just be turned into Space (ie, the /crew doesn't mean anything) then that field can be renamed to make space work.

**Comment by seiyria** [comment]
Same with cost/crew.

**Comment by jsomara** [comment]
I believe 07e9e6e0ccf8c5626229fb4ae551ed405bdf8a84 fixes this
