### ISSUE TITLE
Goofed the configurations again

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#22]
Take the following example:

Patrol craft (I-II). Patrol ships, often used by police and other security organizations, are small ships designed for in-system use. These ships are lightly armed and often lack FTL capability. These vessels are often used for system defense and law-enforcement duties, as well as local rescue operations.

```
Evasive. Patrol craft gain +2 to their DEFENSE score.
Inspector. Patrol craft may make two scanning checks per turn as a single action.
```

So, the hull configuration is Patrol Craft.

It has the Evasive and Inspector traits.

So you’d have a ship something like: Murphy Class VI Patrol Craft

In the stat block (perhaps where you currently have a line of Configuration, you’d then simply say:

Configuration: Evasive, Inspector

**Comment by jsomara** [comment]
and:
(Though if they don’t choose a configuration, might need a default neutral sounding word like “Vessel” to stick in the title bar).

**Comment by seiyria** [comment]
Can't they only have one configuration?

**Comment by jsomara** [comment]
Yes, but the configuration is "patrol craft", not "evasive" and "inspector". patrol graft grants you both of those

**Comment by seiyria** [comment]
So you can only choose one thing, ie, patrol craft. Doing so grants you
evasive and inspection?
