### ISSUE TITLE
Troops/crew quantity selector isn't binding properly to quantity

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#23]
![screenshot 2015-07-23 22 34 14](https://cloud.githubusercontent.com/assets/29121/8868272/075101da-318b-11e5-9d8b-0af25d14dc51.png)

**Comment by seiyria** [comment]
It always starts at 1. If you want to remove more you have to say how much.

**Comment by jsomara** [comment]
oh got it!
