### ISSUE TITLE
Fix operational range calculation

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#28]
Not sure how operational range is being calculated – I have a Class X ship (base range 1000) and 1.6 fuel efficiency, so it should say 1600 parsecs.  It says 4600 instead.

**Comment by seiyria** [comment]
You must be adding something else, and I'm not sure what: http://puu.sh/jlksn/bce18e3dc6.png

A base class X ship with an FTL engine with 1.6 efficiency seems to be calculated correctly. Needs more info.

**Comment by jsomara** [comment]
![image](https://cloud.githubusercontent.com/assets/29121/9563951/607029cc-4e4a-11e5-8a43-31e3bc10820d.png)
