### ISSUE TITLE
Calculate final weight

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#3]
Final weight is a specific number, not a range.

TBD : how to calculate weight

**Comment by jsomara** [comment]
Percentage of CU used as a percentage of the tonnage range.

So if it's 40,000 - 50,000 tons, and you've used exactly 50% of the cargo units, then the tonnage is 45,000 tons.

**Comment by seiyria** [comment]
my concern with this is that weight is currently a string instead of a numerical min/max. thoughts?

**Comment by jsomara** [comment]
Yeah i know, I think you'll have to do some hokey string parsing
