### ISSUE TITLE
Download CSV data live

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#36]
prefix: http://www.enworld.org/woin/components/

cloaks.csv -> :176
computers.csv -> :54 
deflectors.csv -> :70
facilities.csv -> :93
ftl.csv -> :108
hull.csv -> :124
pointdefence.csv -> TBD
sensors.csv -> :148
shiptype.csv -> :136
subluminal.csv -> :159
systems.csv -> :204
weapons.csv -> :187

**Comment by jsomara** [comment]
Point Defences is on :581 / 230 , which I m about to check in

**Comment by jsomara** [comment]
@seiyria make sure these are copied (via gulp) to ./starship_data/ in dist

**Comment by seiyria** [comment]
Right back at'cha!
