### ISSUE TITLE
misc layout issues

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#45]
```
- can we get rid of all the colons everywhere
- there are various places where it says "each power: x" or "each CPU cycles: x" - can we remove the word each?
- the word Passengers should be bold, like Crew and Troops are
- shuttles formatting says "1x Megalight EI93 Shuttle/fighter Bay, (Room for : 4shuttles or fighters)".  What it should say is: “Shuttles 4 (1 x EI93 Shuttle/fighter Bay); Fighters 4 (1 x EI93 Shuttle/fighter Bay)” (i.e. they should be counted separately and formatted a little differently).
- On iOs that left menu is dark blue text on a dark background, so it’s a bit hard to read
```

**Comment by seiyria** [comment]
- unsure of colon situation - some rewording might be necessary and specific colons to adjust are 100% necessary
- shuttles and fighters never appear to have a different number so I'm unsure why they're being displayed separately.

**Comment by Morrus** [comment]
Shuttles and fighters don't have a different number, but they should do. The stat block needs to display each separately in the format:

Shuttlecraft X (y \* bay type); Fighters Z (w \* bay type)

**Comment by seiyria** [comment]
Right, so there is no way right now to determine if they should be separate, so all of the numbers will be the exact same and the data will be duplicated. Either this would require the data format to change or something, but as of right now there is no distinction between the two.

**Comment by Morrus** [comment]
That's because the input does not allow you to select bays for each separately. The issue is in the input interface. It should allow two separate selections, one for shuttles and one for fighters. Both would use the same CSV.

**Comment by herosheets-codeship** [comment]
Having multiple craft types in the hangar page needs its own issue, as it is quite a substantial change. Closing this one as I believe the rest of the requirements are satisfied
