### ISSUE TITLE
Support multiple craft types in hangars page

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#51]
A user needs to be able to assign a hangar to either shuttles or fighters in the user interface, as a single hangar cannot contain both types. The choice needs to be reflected in the ship view as well

**Comment by jsomara** [comment]
Additional formatting issue:

Hangars are reporting the number of shuttles as the same as the number of bays. It says Shuttles & Fighters 8 ( 8x Megalight EI93 Shuttle/fighter Bay, ) where that should be Shuttles & Fighters 8 ( 2x Megalight EI93 Shuttle/fighter Bay, )  (though weren’t we splitting them into shuttles and fighters?)
