### ISSUE TITLE
Point defense not costing anything

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#52]

**Comment by seiyria** [comment]
needs more info, they are decrementing costs appropriately for me.

**Comment by Morrus** [comment]
Image attached.  The Space and Cost columns are empty.  The only thing that increments is CPU.

**Comment by seiyria** [comment]
your image did not attach. however, here is my image of this working as I assume it's intended:

![](http://puu.sh/kzquV/b0c2d80d9a.png)

**Comment by Morrus** [comment]
That’s not what I see.  There is nothing under space or Cost/point.

**Comment by Morrus** [comment]
![pointdefenses](https://cloud.githubusercontent.com/assets/14054539/10284507/401f359c-6b7c-11e5-8f86-9ba06918d1c4.jpg)
![pd2](https://cloud.githubusercontent.com/assets/14054539/10284534/627504c8-6b7c-11e5-9e24-23e0f0f82617.jpg)

**Comment by seiyria** [comment]
That's a problem with the data, then, and I'll have to defer to @jsomara on that.

**Comment by jsomara** [comment]
This is weird, as of right now in the production system I don't see those missing columns. Are you guys still seeing this? 

<img width="931" alt="screenshot 2015-10-11 17 23 22" src="https://cloud.githubusercontent.com/assets/29121/10420011/cde32f40-703c-11e5-8f0d-9428c7713bc0.png">

**Comment by Morrus** [comment]
Yes. No space or cost.

**Comment by Morrus** [comment]
I’d add that not only am I not seeing those columns, the actual weapons have completely different names on my screen. It’s like it’s an entirely different list.

**Comment by seiyria** [comment]
@jsomara it feels like a caching problem.

Anyway, @Morrus the problem here is that you have two columns - CU and Cost/point. They should be Space and Cost respectively. See [here](https://github.com/herosheets/woin-starships/blob/starship/starship_data/cloaks.csv) for an example.

**Comment by Morrus** [comment]
The CSV definitely says Space and Cost.

**Comment by seiyria** [comment]
I can assure you it does not.

![](http://i.imgur.com/LofTHKm.png)

**Comment by Morrus** [comment]
Oh, wait, I'm looking at the FTP'd CSV.  I forgot we weren't using those any more!  Still, those headers there can be changed quickly.  Will that fix the issue?

**Comment by seiyria** [comment]
I'm under the impression that it will.

**Comment by Morrus** [comment]
Might want to hold off closing it until we verify it’s actually working?  All this closing and opening and closing and opening!

**Comment by Morrus** [comment]
Okey dokey.  Headers are changed!

**Comment by Morrus** [comment]
And we have liftoff!  It’s working – the space and cost are now being charged correctly.  Awesome!  

(It’s still adding directly to DEFENSE though, resulting in enormous DEFENSE scores, but that’s another thread on here).
