### ISSUE TITLE
Systems display has extraneous (1)

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#55]
All the stuff under systems doesn't need that extra (1) in parenthesis after it. Only the stuff from the facilities tab needs that. Again, not a big deal, just a minor format thing.

**Comment by seiyria** [comment]
Please provide specific examples with screenshots so we can get this right the first time.

**Comment by Morrus** [comment]
I'll try to when I next get to a computer.

**Comment by Morrus** [comment]
![parentheticals](https://cloud.githubusercontent.com/assets/14054539/10769806/d3c9f75e-7cdf-11e5-9856-8fc0eecfbae3.jpg)

Here you go.

**Comment by seiyria** [comment]
The "also defense isn't showing" is not related to this issue. @jsomara - you tweaked defense lately, did that break something?
