### ISSUE TITLE
Add vehicles to hangar type

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#56]
Add an additional type to hangars, "Vehicles"

**Comment by seiyria** [comment]
How do I know what's a vehicle hangar or what's a shuttle or what's a fighter? Can literally any hangar be used for anything? Will the names change to accommodate this?

**Comment by Morrus** [comment]
Same as when fighters were added to shuttles. Any hangar can be used for each.

**Comment by Morrus** [comment]
I notice this got marked as "closed" but I'm not seeing the vehicles?  Is it just waiting to be deployed?

**Comment by seiyria** [comment]
I actually don't remember closing this, my mistake.
