### ISSUE TITLE
Point Defenses aren't displaying Aura in their details. 

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#57]
Point Defenses aren't displaying Aura in their details.

**Comment by seiyria** [comment]
What does this mean? Is there a separate Aura column? Is this a detail that's omitted from the ship view?

**Comment by Morrus** [comment]
Yes, there's an aura column in the CSV. It's not showing in the ship star block.

**Comment by jsomara** [comment]
How should I display the Aura here? 
- total of all Aura values, 
- ...vs. missiles and fighters, Aura: 2),
- some other way? 

Just let me know how that should be presented

**Comment by Morrus** [comment]
It'd be a different figure for each point defense weapon type. I can't imagine multiple types would ever be used much, but if so, each has its own aura.

**Comment by jsomara** [comment]
Is the aura multiplied by the quantity, or is it static?

**Comment by Morrus** [comment]
Just static!

**Comment by jsomara** [comment]
Great, that is super easy

**Comment by herosheets-codeship** [comment]
Feature added in previous commit
