### ISSUE TITLE
Separate power plant block from computer display

### ISSUE THREAD

**Issue by herosheets-codeship** [herosheets/woin-starships#58]
In Computers there's a section of Power Plants. That should really be its own tab and line in the stat block.

**Comment by Morrus** [comment]
I think if we could quickly slip this one in, we can open it up to beta testing.

**Comment by jsomara** [comment]
I see the new sections in the CSVs. You say this should be its own tab, meaning you'd like a separate power plant section beneath Command & Control in the left navigation?

Can a user select both a computer and a power plant?

What about the Navigation Computers, AI and Fasa Trek - which tab will these end up on? The first two sound like sub-categories of "Computers"

Assuming you want these as a separate section, go ahead and make a powerplants.csv file and move the appropriate rows over there. Then I would add a "category" column to each, and put the appropriate category in that column (AI, Fasa Trek, etc)

**Comment by Morrus** [comment]
Yeah, just the power plants bit - the others are just types of control computer split up to ease navigation. No need to worry about doing anything to navigation computers, AI, and FASA Trek.

You can select both computer and power plant. Originally they were supposed to give different resources (CPU and Power) but they got smooshed into just CPU.

**Comment by jsomara** [comment]
Got it - I just split these out and pushed it, so just create powerplants.csv with the info you'd like and it should work. You'll need to edit the helper text however you see fit as well, it's copied from Computers.

**Comment by Morrus** [comment]
Cool. Done! I renamed the table headers on that new HTML file, too, to say Power Plants -- I don't know if that will affect anything,  but if it breaks, that will probably be why!

**Comment by Morrus** [comment]
Yeah, it didn’t like me changing the headers on the table to Power Plant!  At least, I think that’s what happened – the power plants file isn’t working correctly, but I’m pretty sure that’s because of me.  Hopefully something you can fix easily!
