### ISSUE TITLE
Defence Not Showing

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#61]
In this ship, there is no DEFENSE score showing.

Also, it's a Class 1 ship, but the Superstructure is showing as 6. SS (assuming no additional SS is purchased) is 3 x ship class.

Junker Class I Courier
Weight 2,840 tons; Cargo Units 50 (27 available; capacity 1350 tons)
Hull Class I (INIT 0)
Traits Fast, Silent-running
Crew 4 (cost 800cr/m); Troops 0; Passengers 0 (0 standard, 0 luxury)
Command & Control Systems
Computers 1x Highwatch SM-1 Command Computer (CPU cycles: 8; max FTL: 2; checks: +0d6)
Power Plants
Sensors Chen-Collins SS-2 (range 4; check +0d6)
Engine & Propulsion Data
Subluminal 1x Newline-Silverwide Systems SL-1 Liquid Fuel Rocket (power: 11; SPEED: 5.5; fuel efficiency: 0.5)
FTL 1x Cui-Green Alliance SH-1 Hyperdrive (power: 4; FTL: 2.0; fuel efficiency: 0.8) 
Backup FTL -
Operational Range 0.8 parsecs
Defensive Data
Superstructure 6 DEFENSE ELECTRONIC DEFENSE 10
Armor -
Shields 1x DayCorp Systems SSN-1 Navigational Shield Generator (power 1; SOAK 0)
Point Defenses -
Weapons Data
Facilities
Luxury 100% (Adequate: -)
Facilities Messhall (4),
General Systems
Fueling -
Electronic Warfare -
Tractor Beams -
Cloaking Device -
Engineering -
Hangars & Bays
Shuttles 0 ( )
Fighters 0 ( )
Vehicles 0 ( )
Market Value 39 MCr

**Comment by Morrus** [comment]
Added data just in case it helps. Another example of DEFENSE not showing:

Class XVIII
Weight 460,467 tons; Cargo Units 5000 (3953.3 available; capacity 197665 tons)
Hull Class XVIII (INIT -3d6)
Traits 
Crew 4250 (cost 850000cr/m); Troops 0; Passengers 0 (0 standard, 0 luxury)
Command & Control Systems
Computers 3x Newstellar EM-1 Command Computer (CPU cycles: 16; max FTL: 4; checks: +0d6)
Sensors Interstellar Enterprises MS-2 (range 6; check +0d6)
Engine & Propulsion Data
Subluminal 4x SunCo Livestock LL-2 Liquid Fuel Rocket (power: 30; SPEED: 6.7; fuel efficiency: 0.6)
FTL 2x Panwatch-Microbeam EA-1 Antimatter Engine (power: 32; FTL: 3.6; fuel efficiency: 1) 
Backup FTL 2x White AgriSpace MA-1 Antimatter Engine (power: 15; FTL: 1.7; fuel efficiency: 1)
Operational Range 5832 parsecs
Defensive Data
Superstructure 54 DEFENSE E-DEFENSE 10
Armor -
Shields 4x Westdyne Enterprises ESN-2 Cruiser Navishield Solution (power 128; SOAK 7) 2x Huang DEFENSE GSM-2 Ultimate Series Combat Shield (power 232; SOAK 12)
Point Defenses 10x Hakimoto AL-47 Kinetic Energy Flak Weapon (+2 vs. missiles and fighters, Aura: 5)
Weapons Data
Facilities
Luxury 1% (Spartan: -2d6)
Facilities Cabin, Hotbunk (4), Casino (1), Cabin, Luxury/Environmental (1), Cabin, Double (1), Messhall (21),
General Systems
Fueling 1x Black Hole Products P40 Fuel Scoop,
Electronic Warfare 1x Ultralight BMS55 Jamming System,
Tractor Beams 1x Phylon C5 Tractor Beam Emitter,
Cloaking Device 1x Waywatch BI95 Cloaking Device,
Engineering 1x Newwatch IE17 Remote Repair Bay,
Hangars & Bays
Shuttles 4 ( 1x Megalight EI93 Hangar Deck, )
Fighters 1 ( 1x Parsec Systems ZM2 Single Shuttle Bay, )
Vehicles 32 ( 1x Waydyne Vehicle Shuttle/Fighter Bay, )
Market Value 95033.1 MCr

**Comment by seiyria** [comment]
In the future, we probably only need the relevant section and not the entire dump. I had to scan the whole thing to figure out where defense was supposed to be. A screenshot would also suffice in these cases.

Additionally, when you say "also, [...]" that means you should probably open up a separate issue detailing that particular issue, or it will get lost.

**Comment by Morrus** [comment]
The SS thing was, indeed, opened as a separate issue and I believe Jordan has fixed it.

**Comment by jsomara** [comment]
Correct, https://github.com/herosheets/woin-starships/issues/70

**Comment by Morrus** [comment]
I include all the data because I don't know if something else might be interfering with the issue. In the past, you guys have asked me to do that. I'm happy to report less info, whatever is easiest for you to find bugs with.

**Comment by seiyria** [comment]
What might actually be best is to just include the JSON dump of your ship so we can repro it easier.
