### ISSUE TITLE
Incorrect Speed

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#62]
The below speed is incorrect. 18/3=6, not 4.5.

Aphid Class III Transport
Weight 17,400 tons; Cargo Units 250 (190 available; capacity 9500 tons)
Hull Class III (INIT 0)
Traits Skeleton Crew
Crew 7 (cost 1400cr/m); Troops 0; Passengers 0 (0 standard, 0 luxury)
Command & Control Systems
Computers 1x Highwatch SM-1 Command Computer (CPU cycles: 8; max FTL: 2; checks: +0d6)
Power Plants
Sensors Chen-Collins SS-2 (range 4; check +0d6)
Engine & Propulsion Data
Subluminal 1x Oshiro Shipping MI-1 Ion Engine (power: 18; SPEED: 4.5; fuel efficiency: 1.4)
FTL -
Operational Range parsecs
Defensive Data
Superstructure 12 DEFENSE ELECTRONIC DEFENSE 10
Armor -
Shields
Point Defenses -
Weapons Data
Facilities
Luxury 120% (Adequate: -)
Facilities Sickbay (1), Cabin, Double (8), Messhall (4),
General Systems
Fueling -
Electronic Warfare -
Tractor Beams -
Cloaking Device -
Engineering -
Hangars & Bays
Shuttles 1 ( 1x Parsec Systems ZM2 Single Shuttle Bay, )
Fighters 0 ( )
Vehicles 0 ( )
Market Value 497.4 MCr

**Comment by jsomara** [comment]
This is odd, I just set this up on my own and I got 6.

Hull Class III (INIT -)
Subluminal 1x Oshiro Shipping MI-1 ion engine (power: 18; SPEED: 6.0; fuel efficiency: 1.4)

There must be something else adding in to that, but the calculation in the code is really simple...Pushing some debug info to help figure this out

**Comment by jsomara** [comment]
Got it - I think every Hull class on the remote server (but not locally) are off by 1. The server thinks the hull class is 4, not 3, even though you picked 4
