### ISSUE TITLE
Fuel Bay Alteration Does Nothing

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#68]
On top of the fuel bay alteration not being subtracted from the available CU's in the tool (it shows as 0 size on the builder table), it also doesn't affect operational range in the builder. I can add, then subtract, tons of fuel bay alterations, and the operational range for the ship stays the same.

Note that it says 0 CUs in the table, but that's because it can be a positive or negative value. I could replace that entry with two entires (one +1 CU, one -1 CU) if that would help. It still needs to feed into the operational range, though.

**Comment by jsomara** [comment]
The fuel bay alterations are not currently programmed to modify operational range. The current formula is:

(ship class^3) \* (fuel efficiency of first engine)

Where does that belong in there?

**Comment by Morrus** [comment]
It's a simple 1:1 increase in range. If you select 150 fuel bay alterations, you just add +150 to the operational range (before applying the fuel efficiency multiplier).

**Comment by seiyria** [comment]
For this I would like a simple ship dump to fully understand what's going on.

**Comment by Morrus** [comment]
Nothing is going on (yet). It's not so much a bug, as a feature from the rules which got missed.
Every "unit" of fuel bay alteration that is purchased should increase the Operational Range by 1 parsec (before the engine's efficiency multiplier is applied). 

Date: Tue, 7 Jun 2016 14:33:57 -0700

**Comment by Morrus** [comment]
As far as I can tell, it doesn't. I just added 200+ fuel bay alterations to a ship, and the operational range did not change.

<img width="983" alt="screen shot 2016-06-08 at 11 45 02" src="https://cloud.githubusercontent.com/assets/14054539/15891867/9543ab98-2d6e-11e6-8802-492d4ba741b5.png">

**Comment by seiyria** [comment]
Ok, so it's looking for "Fuel bay alteration" on my side, but I see you have it as "Fuel Bay Alteration" - it's case sensitive, so what do you want it to be?

**Comment by Morrus** [comment]
As shown in the data csv, please.

Date: Wed, 8 Jun 2016 06:25:00 -0700
