### ISSUE TITLE
Superstructure - not loading CSV correctly

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#69]
Superstructure starts at 3x ship class. Often it shows "none" (example below). Additional superstructure added in the Superstructure tab is added to this. 

Also, the superstructure.csv does not seem to match the actual superstructure tab.  The csv  (correctly) says:

Base (free) SS = 3 x ship class
https://github.com/herosheets/woin-starships/blob/starship/starship_data/superstructure.csv

While the tab says:

Base (free) SS = ship class
http://starships.enworld.org/#/superstructure

So that seems to be being populated from somewhere other than superstructure.csv.

Class IV Frigate
Weight 25,000 tons; Cargo Units 400 (400 available; capacity 20000 tons)
Hull Class IV (INIT 0)
Traits Gunboat
Crew 12 (cost 2400cr/m); Troops 0; Passengers 0 (0 standard, 0 luxury)
Command & Control Systems
Computers
Sensors none (range 0; check 0)
Engine & Propulsion Data
Subluminal
FTL -
Operational Range parsecs
Defensive Data
Superstructure none DEFENSE 17 E-DEFENSE 10
Armor -

**Comment by jsomara** [comment]
Gonna split these into two issues; will use this issue to track the concept of not loading from csv

**Comment by jsomara** [comment]
For some reason, we put passengers & superstructures in custom data structures and they're not reading from the CSV. Setting this up
