### ISSUE TITLE
Superstructure Info Addition

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#71]
This isn't a bug, but it'll make things much easier!

On the superstructure page:
http://starships.enworld.org/#/superstructure

Can we add an indication of the vessel's current total SS? I know folks can do it in their head (it's 3 x class plus whatever gets added on that page) but I think that would be a value-added ease of use change. For that matter, indicating the current armor SOAKs on that page would be very useful too. Otherwise I find I'm checking back to the Your Ship tab all the time.

Same for Crew, actually. I find myself switching between tabs a lot there.  And Facilities, for the current LUXURY value.

**Comment by jsomara** [comment]
Ah re-opening I realized that i missed adding SOAK

**Comment by Morrus** [comment]
Just a quick note - the output says:

(undefined

When no armor is yet added.
