### ISSUE TITLE
Save button does not work in Safari

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#73]
Seems OK in Firefox, but using Safari the save json button does nothing.

**Comment by jsomara** [comment]
@Morrus which version of safari did you use to test this?

**Comment by Morrus** [comment]
It's the Mac desktop version, 9.1.

**Comment by jsomara** [comment]
That's the same version I'm running, so I'll check it out soon and let you know. Have you tried Chrome as well? If not, I'll add that to the list.

**Comment by Morrus** [comment]
I don't have Chrome, but I'll grab it and give it a try later.

**Comment by seiyria** [comment]
So here's the thing, Safari sucks. Some relevant discussion here: https://github.com/eligrey/FileSaver.js/issues/129 and here: https://github.com/eligrey/FileSaver.js/issues/12

When clicking Save, Safari users will see their ship data open in a new tab. They have to hit cmd+S, then change the format to "Page source", and then name the file, and hit save that way. It will still work normally in every other browser listed here: https://github.com/eligrey/FileSaver.js#supported-browsers
