### ISSUE TITLE
Crew now wrong

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#75]
Crew is now wrong, but in a totally different way to how it was before. :)

Let me try to explain it again:

The LUXURY calculation uses the total of crew, passengers, troops. 

However, that total should not be displayed in the stat block. The Crew/Troops/Passengers line in the stat block should break that down. It should show three figures: crew, troops, passengers. That entry should not add those numbers together; those numbers are added together only behind the scenes when calculating LUXURY. 

So if I have 7 crew and add 3 passengers, it should not say 10 crew, it should say 7 crew, 3 passengers, 0 troops. However, you would use the value 10 behind the scenes when calculating LUXURY.

**Comment by jsomara** [comment]
Hmm, how you explained it is how it is implemented as far as I can tell. Gonna do some experimenting

**Comment by jsomara** [comment]
I think this is right, isn't it? Check out these screenshots. Started with hull class III, or 5 base crew. Added 5 add'l crew, 5 of each passenger type and 10 troops.

![screenshot 2016-06-09 18 50 20](https://cloud.githubusercontent.com/assets/29121/15952122/2108341e-2e73-11e6-8be4-d32b30be5ab7.png)

![screenshot 2016-06-09 18 50 30](https://cloud.githubusercontent.com/assets/29121/15952124/24b46178-2e73-11e6-9c63-98379810c4b7.png)

**Comment by jsomara** [comment]
Now, the extra crew reminder of "current crew" on the crew page only shows the "total crew" value, not the luxury calculation value. I can have it look exactly like the block from the main ship page, but that seems redundant since the user is already looking at the other passenger values

**Comment by jsomara** [comment]
Something is fishy, I refreshed and the crew value of Hull class III went from 5 to 7, so now the current crew with the same value is 12 instead of 10. Anyway, the rest of that looks the same, and the crew value for the luxury calculation is 32 (12 + 5 + 5 + 10)

Crew 12 (cost 2400cr/m); Troops 10; Passengers 10 (5 standard, 5 luxury)

(below is from a log I wrote, this does not show up in the interface)
Total crew: 12
     + standard Passengers = 17
     + luxury Passengers = 22
     + troops = 32

**Comment by Morrus** [comment]
Huh. OK, that's word.  I'm _sure_ it wasn't doing that before, but you're right. It seems OK; I'll keep an eye on it just in case it was a weird situational thing, but I think it works OK.

(Dunno about the crew value of the Hull class changing though - maybe that's what I saw?)

**Comment by jsomara** [comment]
Will close this for now, please reopen if you see this in actiona gain
