### ISSUE TITLE
FTL speed showing 0

### ISSUE THREAD

**Issue by Morrus** [herosheets/woin-starships#76]
Class III ship, 79 power, showing 0 FTL.  Screenshot attached.

<img width="728" alt="screen shot 2016-06-09 at 13 46 21" src="https://cloud.githubusercontent.com/assets/14054539/15930052/a8d5d69c-2e48-11e6-9cf4-aeef19db22cc.png">

**Comment by jsomara** [comment]
The formula on this guy is :

MAX(totalPower (from ftl engine) / hull class, Max FTL from computer)

In the thing above you haven't chosen a computer, so your maxFTL is 0. If I pick those same stats, I get 0. Then, if I add a computer with a max FTL of 16, it shows me the FTL as being 16. Then, if I add enough computers to make the max FTL 100, it shows me the FTL is 26.3, or 79/3.

So to my estimation that is working as intended, but my formula could be off

**Comment by Morrus** [comment]
Ah, in that case I"m an idiot.  You're right; it was because I didn't include a computer.

However, that does highlight another thing - the max FTLs don't add together with computers. Just like with crew, e-defense, rng inc, soak, defence, and checks, you use the best value.
