### ISSUE TITLE
Hull Configuration Selection

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-starships#8]
Hull configuration.  Only just spotted it!  It’s missing the actual titles of each, so it’s hard to know which to select.  It’s just showing the granted ability.  That’s the “ship type” bit I mean from the title – “Cruiser”, “Scout”, etc.

I believe we need to filter the list of hull configurations based on what class of ship the user chooses

**Comment by seiyria** [comment]
Regarding it being hard to see: it's been moved. I've not addressed anything further.

**Comment by jsomara** [comment]
OK, I think this is a 2 part fix.

Part 1 - add the applicable ship classes to the hull configuration list. Go here to see how they are grouped: http://www.woinrpg.com/starship-hull-class/

Part 2 - make the dropdown filter by the class of ship the user selects. The list from ^ shows which configurations are available to which classes. For example:

Courier (I-II)  
    Fast. Couriers gain +1 to their FTL speed.
    Silent-running. A courier ship can operate stealthily. While this will not protect it from actual scans in the way that a cloaking device might, it can pass unnoticed in a navigational scan when not actively being looked for.

So, Fast and Silent-Running are only available to ship with hulls in I & II. 

There is a method to calculate the ship class called "getHullClassInteger" that should make this easy
